apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/assets-pvc-1
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: assets-pv-1
  storageClassName: ""
