apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/couchdb-pvc-1
  volumeMode: Filesystem
