apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-data-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/openbao-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-init-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/openbao-init

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-tls-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/openbao-tls

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-certs-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/shared-certs

