apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-data-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 127.0.0.1
    path: /data/nfs/platform-data-pvc-1
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-data-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: platform-data-pv-1
  storageClassName: ""
