apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-nfs-pv

spec:
  capacity:
    storage: 10Gi   # must match PVC

  accessModes:
    - ReadWriteMany   # must match PVC

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ""   # same as you want

  nfs:
    path: /data/nfs/postgresql-data-new
    server: 127.0.0.1
