apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-backup-new-pv-11

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ""

  nfs:
    server: 127.0.0.1
    path: /data/nfs/postgresql-backup-new-pvc-11

  volumeMode: Filesystem