apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-1

spec:
  capacity:
    storage: 10Gi   # ✅ matches PVC

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ""

  nfs:
    server: 127.0.0.1
    path: /data/nfs/static-pvc-1

  volumeMode: Filesystem
