apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-defined-template-pv-1

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: ""

  nfs:
    server: 127.0.0.1
    path: /data/nfs/user-defined-template-pvc-1

  volumeMode: Filesystem