apiVersion: batch/v1
kind: Job
metadata:
  name: init-file-copy
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
      - name: helper
        image: alpine/git
        command: ["/bin/sh", "-c"]

        args:
          - |
            set -e

            echo "Cloning repo..."
            git clone https://github.com/jagdishpatil07/GitOps_Repo.git /repo

            cd /repo/FILES

            ###################################
            # NGINX FILES
            ###################################
            echo "Copying nginx configs..."
            mkdir -p /nginx/conf.d
            cp -f nginx/nginx.conf /nginx/nginx.conf
            cp -f nginx/mime.types /nginx/mime.types
            cp -f nginx/blockuseragents.rules /nginx/conf.d/blockuseragents.rules

            ###################################
            # PLATFORM CONFIGS
            ###################################
            echo "Copying platform configs..."
            mkdir -p /platform
            cp -f platform/*.json /platform/ || true
            cp -f platform/allowed_host.txt /platform/ || true

            ###################################
            # POSTGRES CONFIGS
            ###################################
            echo "Copying postgres configs..."
            mkdir -p /postgres/pgdata

            cp -f postgres/postgresql.conf /postgres/pgdata/postgresql.conf
            cp -f postgres/pg_hba.conf /postgres/pgdata/pg_hba.conf

            chmod 600 /postgres/pgdata/* || true

            ###################################
            # DEBUG
            ###################################
            echo "NGINX FILES:"
            ls -l /nginx

            echo "PLATFORM FILES:"
            ls -l /platform

            echo "POSTGRES FILES:"
            ls -l /postgres/pgdata

            echo "File copy completed successfully"

            sleep 5

        volumeMounts:

        - name: nginx-pvc
          mountPath: /nginx

        - name: platform-pvc
          mountPath: /platform

        - name: postgres-pvc
          mountPath: /postgres

      volumes:

      - name: nginx-pvc
        persistentVolumeClaim:
          claimName: nginx-conf-pvc-1

      - name: platform-pvc
        persistentVolumeClaim:
          claimName: platform-configs-pvc-1

      - name: postgres-pvc
        persistentVolumeClaim:
          claimName: postgresql-data-new-pvc-11
