apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: revolutio.azurecr.io/revolutio_kubernetes/kafka:latest
        command:
          - sleep
          - infinity
          
