# ============================================================
# RQ SCHEDULER
# ============================================================
rqscheduler:
  replicaCount: 1

  image: revolutio.azurecr.io/revolutio_kubernetes/rqscheduler:latest

  configMap: envs-production-web

  pvc:
    static: static-pvc-1
    templates: user-defined-template-pvc-2
    platformConfigs: platform-configs-pvc-1

  resources:
    requests:
      cpu: "100m"
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 512Mi
