apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-app-migration
  namespace: myapp
  labels:
    service: worker-app-migration

spec:
  replicas: 1

  selector:
    matchLabels:
      service: worker-app-migration

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

  template:
    metadata:
      labels:
        service: worker-app-migration

    spec:
      restartPolicy: Always

      imagePullSecrets:
        - name: acr-secret

      securityContext:
        runAsUser: 70070
        runAsNonRoot: true
        fsGroup: 70070

      containers:
        - name: rqworker

          image: revolutio.azurecr.io/revolutio_kubernetes/revolutio:latest
          imagePullPolicy: Always

          securityContext:
            runAsUser: 70070
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          args:
            - /rqworker/start-app-migration

          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)
