apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-alerts
  namespace: {{ .Values.namespace }}
  labels:
    app: worker-alerts

spec:
  replicas: {{ .Values.workerAlerts.replicaCount }}

  selector:
    matchLabels:
      app: worker-alerts

  template:
    metadata:
      labels:
        app: worker-alerts

    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}

      # OpenShift safe
      securityContext: {}

      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: {{ .Values.workerAlerts.pvc.static }}

        - name: templates-storage
          persistentVolumeClaim:
            claimName: {{ .Values.workerAlerts.pvc.templates }}

        - name: platformconfig-storage
          persistentVolumeClaim:
            claimName: {{ .Values.workerAlerts.pvc.platformConfigs }}

        - name: computation-storage
          persistentVolumeClaim:
            claimName: {{ .Values.workerAlerts.pvc.computation }}

      containers:
        - name: worker-alerts
          image: "{{ .Values.workerAlerts.image }}"
          imagePullPolicy: Always

          args:
            - /rqworker/start-alerts

          resources:
            requests:
              cpu: {{ .Values.workerAlerts.resources.requests.cpu }}
              memory: {{ .Values.workerAlerts.resources.requests.memory }}
            limits:
              cpu: {{ .Values.workerAlerts.resources.limits.cpu }}
              memory: {{ .Values.workerAlerts.resources.limits.memory }}

          env:
            - name: DATABASE_URL
              value: {{ .Values.workerAlerts.databaseUrl | quote }}
            - name: REDIS_URL
              value: {{ .Values.workerAlerts.redisUrl | quote }}

          envFrom:
            - configMapRef:
                name: {{ .Values.workerAlerts.configMaps.web }}
            - configMapRef:
                name: {{ .Values.workerAlerts.configMaps.postgres }}
            - secretRef:
                name: {{ .Values.workerAlerts.secrets.web }}
            - secretRef:
                name: {{ .Values.workerAlerts.secrets.postgres }}

          volumeMounts:
            - name: static-storage
              mountPath: /opt/revolutio/static

            - name: templates-storage
              mountPath: /opt/revolutio/Core/templates/user_defined_template

            - name: platformconfig-storage
              mountPath: /opt/revolutio/Platform_Configs

            - name: computation-storage
              mountPath: /opt/revolutio/Computation_Temp_Storage

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst