apiVersion: v1
kind: Service
metadata:
  name: arrowflight
  namespace: {{ .Values.namespace }}

spec:
  selector:
    service: arrowflight

  ports:
    - name: flight
      port: 8815
      targetPort: 8815

  type: ClusterIP
