apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  labels:
    service: nginx

spec:
  type: NodePort

  selector:
    service: nginx

  ports:
    - name: https
      port: 443           # ? Service port
      targetPort: 443     # ? Must match nginx listen 443
      protocol: TCP
      nodePort: 30007     # ? External access
