apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: myapp
spec:
  selector:
    app: openbao
  ports:
  - name: https
    protocol: TCP
    port: 8200
    targetPort: 8200
  - name: cluster
    protocol: TCP
    port: 8201
    targetPort: 8201
  type: ClusterIP
