apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgbouncer

spec:
  selector:
    app: pgbouncer

  ports:
    - name: pgbouncer
      port: 5432
      targetPort: 5432
      protocol: TCP

  type: ClusterIP