apiVersion: v1
kind: Service
metadata:
  name: postgres-core
  namespace: myapp

spec:
  selector:
    app: postgres-core

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

  type: ClusterIP
