apiVersion: v1
kind: Service
metadata:
  name: sockets
  namespace: {{ .Values.namespace }}
  labels:
    service: sockets

spec:
  type: ClusterIP

  selector:
    service: sockets

  ports:
    - name: uvicorn
      protocol: TCP
      port: 5000
      targetPort: uvicorn
