apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: computation-storage-pvc-1
  namespace: myapp

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: ""

  volumeName: computation-storage-pv-1   # ✅ FIXED (STRICT MATCH)

  resources:
    requests:
      storage: 5Gi

  volumeMode: Filesystem