apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-data-pv-1
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-init-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-init-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-tls-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-tls-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-certs-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: shared-certs-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-postgres-core-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-postgres-core-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-redis-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-redis-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-keydb-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-keydb-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-couchdb-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-couchdb-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-revolutio-app-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-revolutio-app-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-pgbouncer1-new-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-pgbouncer1-new-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-pgbouncer1-app-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-pgbouncer1-app-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-dashboard-api-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-dashboard-api-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-datahub-api-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-datahub-api-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-postgres-backup-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-postgres-backup-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-pgbackrest-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-pgbackrest-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-rqscheduler-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-rqscheduler-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-kong-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-kong-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-rabbitmq-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-rabbitmq-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-approle-platform-migrator-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-approle-platform-migrator-pv-1
  resources:
    requests:
      storage: 1Gi
