apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-data-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-data-pv-1
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-init-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-init-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-tls-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: openbao-tls-pv-1
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-certs-pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: shared-certs-pv-1
  resources:
    requests:
      storage: 1Gi

---
