apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-core-pvc
  namespace: myapp
spec:
  storageClassName: ""
  volumeName: postgresql-data-core-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup-core-pvc
  namespace: myapp
spec:
  storageClassName: ""
  volumeName: postgresql-backup-core-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-core-socket-pvc
  namespace: myapp
spec:
  storageClassName: ""
  volumeName: postgres-core-socket-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
