apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-defined-template-pvc-2
  namespace: myapp

spec:
  accessModes:
    - ReadWriteMany


  storageClassName: ""

  volumeName: user-defined-template-pv-2

  resources:
    requests:
      storage: 5Gi
