apiVersion: v1
kind: Secret
metadata:
  name: secrets-production-redis
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  REDIS_PASSWORD: "redissecretpassword"
  KEYDB_PASSWORD: "rediskeydbsecretpassword"
  REDIS_PASSWORD_SCHEDULER: "redisschedulersecretpassword"
