apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}

data:
  postgresql.conf: |
{{ .Files.Get "configs/postgresql.conf" | indent 4 }}

  pg_hba.conf: |
{{ .Files.Get "configs/pg_hba.conf" | indent 4 }}