apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres15-new
  namespace: myapp

spec:
  replicas: 1

  serviceName: postgres15-new

  selector:
    matchLabels:
      service: postgres15-new

  template:
    metadata:
      labels:
        service: postgres15-new

    spec:
      imagePullSecrets:
        - name: acr-secret

      securityContext:
        fsGroup: 1000860000

      volumes:
        - name: postgresql-data-new
          persistentVolumeClaim:
            claimName: postgresql-data-new-pvc-11

        - name: postgresql-backups-new
          persistentVolumeClaim:
            claimName: postgresql-backup-new-pvc-11

      containers:

        - name: postgres15

          image: revolutio.azurecr.io/revolutio_kubernetes/postgres:15-bullseye

          imagePullPolicy: Always

          ports:
            - name: postgredb
              containerPort: 5432
              protocol: TCP

          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          envFrom:
            - configMapRef:
                name: envs-production-postgres-new

            - secretRef:
                name: secrets-production-postgres-new

          volumeMounts:

            - name: postgresql-data-new
              mountPath: /var/lib/postgresql/data

            - name: postgresql-backups-new
              mountPath: /backups

          args:
            - "-c"
            - shared_buffers=3GB
            - "-c"
            - work_mem=64MB
            - "-c"
            - maintenance_work_mem=1GB
            - "-c"
            - effective_io_concurrency=100
            - "-c"
            - wal_compression=on
            - "-c"
            - max_wal_size=1GB
            - "-c"
            - min_wal_size=80MB
            - "-c"
            - log_statement=all
            - "-c"
            - autovacuum_max_workers=5
            - "-c"
            - autovacuum_vacuum_cost_limit=1000
            - "-c"
            - idle_in_transaction_session_timeout=240s

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler

  podManagementPolicy: OrderedReady

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

  revisionHistoryLimit: 10

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
